# Generated by Django 2.2.10 on 2024-04-30 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_auto_20211226_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 3, 34, 17, 560411, tzinfo=utc)),
        ),
    ]
