# Generated by Django 2.2.10 on 2024-05-02 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_auto_20240502_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 7, 32, 35, 945334, tzinfo=utc)),
        ),
    ]
