# Generated by Django 2.2.10 on 2024-05-03 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0037_auto_20240502_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.Account')),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum overdraft limit allowed for the account', max_digits=10)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged per transaction', max_digits=6)),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum amount that can be withdrawn in a day', max_digits=10)),
            ],
            bases=('book.account',),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 2, 28, 22, 319151, tzinfo=utc)),
        ),
    ]
