# Generated by Django 2.2.10 on 2024-05-04 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0039_auto_20240503_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 4, 18, 29, 255893, tzinfo=utc)),
        ),
    ]
